#!/bin/zsh
# Embeds ShaderTypes.h + the Metal sources into a Swift string so the app compiles its shaders at runtime.
set -euo pipefail
root=${0:A:h:h}
out=$root/Sources/FractalKit/Generated/ShaderSource.swift
mkdir -p ${out:h}
tmp=$(mktemp)
{
  print -r -- '// Generated by scripts/gen_shaders.sh from Sources/CFractal/include/ShaderTypes.h and Sources/FractalKit/Shaders. Do not edit.'
  print -r -- 'let fractalShaderSource = #"""'
  cat $root/Sources/CFractal/include/ShaderTypes.h
  for f in $root/Sources/FractalKit/Shaders/*.metal; do cat $f; done
  print -r -- '"""#'
} > $tmp
if ! cmp -s $tmp $out 2>/dev/null; then mv $tmp $out; else rm $tmp; fi
